# Generated by Django 4.0.4 on 2022-09-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_alter_itensfeira_feirante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feirantes',
        ),
    ]
