# Generated by Django 3.2.8 on 2022-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensfeira',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/imagens/itens'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/imagens/', verbose_name='foto'),
        ),
    ]
