# Generated by Django 4.0.4 on 2022-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221021_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensfeira',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itens'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='foto'),
        ),
    ]
